name: Translate README

on:
  push:
    branches:
      - main
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          repo-token: ${{ secrets.README_REPO_SECRET }}
      - name: Adding README - Portuguese
        uses: dephraiim/translate-readme@main
        with:
          LANG: pt